### ISSUE TITLE
Error in data request

### ISSUE THREAD

**Issue by mnemo70** [coolchip/luxtronik2#11]
Hi,

thanks for your module. I tried it on my AIT WZS82K3M (software version 3.84.3 on port 8889), but the module threw an exception:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 4
    at boundsError (internal/buffer.js:81:9)
    at Buffer.readInt32BE (internal/buffer.js:477:5)
    at Luxtronik.<anonymous> (/Users/tm/Documents/Dev/luxtronik/node_modules/luxtronik2/luxtronik.js:406:37)

```
This is caused by the "data" event function only receiving 4 bytes at first, but it expects and tries to evaluate the complete response.

I implemented a crude workaround. It fills a "dataBuffer" with the received data (in 2 events) and only processes the data when more than 4 bytes were received. This makes the module work with my heatpump.

The same applies to writing data (first data event receives 4 bytes, second event then receives the final 4 bytes), but strangely this only works for me when **not** reading all data before.

```
Luxtronik.prototype._nextJob = function () {
    if (this.receivy.jobs.length > 0) {
        this.receivy.activeCommand = 0;
// NEXT LINE ADDED:
        this.dataBuffer = undefined;
        sendData(this.client, [this.receivy.jobs.shift(), 0]);

```

```
        if(this.dataBuffer === undefined) {
            this.dataBuffer = data;
        }
        else {
            this.dataBuffer = Buffer.concat([this.dataBuffer, data]);
        }
        if(data.length > 4) {
            data = this.dataBuffer;
            if (this.receivy.activeCommand === 0) {
                const commandEcho = data.readInt32BE(0);
                ...
        }
    }.bind(this));

    this.client.on('close', function () {});
};

```

**Comment by UncleSamSwiss** [comment]
I have the same issue with my CTA Areoheat 16iL. It sends the data in two or three batches, always with the "echo" as a single four-byte packet. I verified this with Wireshark.

My workaround for now is to have a tiny TCP proxy in-between that just caches response data for 100ms, so I'm only forwarding entire responses.

It would be great, if you could fix this.

**Comment by pscheblein** [comment]
I have the same problem "RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range". Would it be possible to post the complete "Workaround Script"? Or even better would it be possible to customize the original script.

**Comment by mnemo70** [comment]
My code snippets in my first post were the complete workaround. @macrauder implemented it in his gist, thank you. My Node-RED crashes after a few minutes when my workaround is used, so there is either something else wrong with it or it's a deeper problem with the module.

**Comment by coolchip** [comment]
It would be great if we find a solution to prevent the lib to throw this error. Perhaps someone will add a pull reqest. Or someone is able describe me what I have to do.

**Comment by coolchip** [comment]
I have copied the workaround of @mnemo70 and @macrauder from [here](https://gist.github.com/macrauder/5cac8b4e6231855238f093b3060b48e7). Hope this is okay. 
I've created a branch for this: https://github.com/coolchip/luxtronik2/blob/fixOutOfRangeError/luxtronik.js

Can anybody confirm that this fixes the problem?

**Comment by UncleSamSwiss** [comment]
Thanks for the fix.

I tested it in my [ioBroker adapter](https://github.com/UncleSamSwiss/ioBroker.luxtronik2) and it works most of the time. Unfortunately sometimes I get the following exception:
```text
Exception has occurred: TypeError: Cannot read property 'payload' of undefined
  at Luxtronik._processData (/workspace/node_modules/luxtronik2/luxtronik.js:265:53)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
Reason for this is the expression `const heatpumpVisibility = this.receivy['3005'].payload;` as `this.receivy['3005']` doesn't exist (when the exception happens - otherwise it seems to work fine).

Now, you could just set `heatpumpVisibility` to `undefined`, but I'm not sure if this wouldn't mask the real problem.

**Comment by UncleSamSwiss** [comment]
Upon further investigation, it seems that you are still not getting the entire 3005 message.
I simply re-enabled my [caching proxy](https://github.com/UncleSamSwiss/ioBroker.luxtronik2/blob/08f6bae671112e2610109d84b0fbc9b31f20656f/src/main.ts#L187-L234) (which waits 100ms for no additional data to arrive) and the above exception doesn't occur anymore.

Of course my proxy is not the solution, but for me it is a nice workaround without changing your code.

**Comment by UncleSamSwiss** [comment]
Looking at Wireshark when the error occurs, I see that you are only requesting `00 00 0b bb` and `00 00 0b bc`. So the request for 3005 is missing completely.

Below you see a screenshot of the diff of a working (left) and not working (right) hex dump of Wireshark:
![image](https://user-images.githubusercontent.com/7595126/103480065-5df8f600-4dd2-11eb-97da-29bd8fec9352.png)

The problem seems to be that your requests for 3004 and 3005 somehow end up in the same packet (see sending packet `0000000C`). I haven't had a look at the code why this could happen.

**Comment by Alkaramazov** [comment]
Hi,
It seems I have the same issue :

`internal/buffer.js:49
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 4
    at boundsError (internal/buffer.js:49:9)
    at Uint8Array.readInt32BE (internal/buffer.js:437:5)
    at Luxtronik.<anonymous> (/node_modules/luxtronik2/luxtronik.js:409:37)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

> I have copied the workaround of @mnemo70 and @macrauder from [here](https://gist.github.com/macrauder/5cac8b4e6231855238f093b3060b48e7). Hope this is okay.
> I've created a branch for this: https://github.com/coolchip/luxtronik2/blob/fixOutOfRangeError/luxtronik.js
> 
> Can anybody confirm that this fixes the problem?

I've tried this branch, seems working fine by now.

Regards

**Comment by mnemo70** [comment]
> I have copied the workaround of @mnemo70 and @macrauder from [here](https://gist.github.com/macrauder/5cac8b4e6231855238f093b3060b48e7). Hope this is okay.
> I've created a branch for this: https://github.com/coolchip/luxtronik2/blob/fixOutOfRangeError/luxtronik.js
> 
> Can anybody confirm that this fixes the problem?

I tried the fix on the command line and it worked. After incorporating the new lib into Node-RED though, the previously problem occurs - Node-RED completely crashes after some time. This is probably caused by the communication hiccup detected by @UncleSamSwiss [above](https://github.com/coolchip/luxtronik2/issues/11#issuecomment-753619552).

I'd really like to provide a fix, but I lack understanding the inner workings of the lib and communication (plus the time). :-(

**Comment by Alkaramazov** [comment]
Well, the first workaround fixed the first issue.
But now, I also have the same exception as @UncleSamSwiss :
`const heatpumpVisibility = this.receivy['3005'].payload;
TypeError: Cannot read property 'payload' of undefined
    at Luxtronik._processData (/node_modules/luxtronik2/luxtronik.js:268:53)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

It always happens when I execute "pump.read" function (as in Luxtronik2 examples) **for the second time**. I'm able to read values at the first execution, but it crashed at the second execution.

I do not want to implement a proxy... ;-)
Does @coolchip have a better idea ?

Thanks and congratulations for this nice job

**Comment by mnemo70** [comment]
This is just an entry to explain what's happening. I'll try to find a real solution.

When adding some logging to the "on data" function and requesting data every 5 seconds in Node-RED, one can see that the data arrives mostly in multiple events and then it's down to sheer coincidence how many events occur and how many bytes arrive in each of them. On my heatpump, there should be 4500 bytes for job 0 (command 3003).

When the "payload of undefined" error occurs, the 4500 bytes are not collected in full for the first read job and the remaining 152 bytes are processed in the next job (for command 3004, which should receive 1048 bytes), thus shifting the remaining data down by one in the processing queue. At the end of the jobs the connection is closed (`this.client`), but there's still data, resulting in another "on data" event, but no more job and connection to process it, resulting in the exception.

I think the solution would be to implement a delayed timeout function, which waits for e.g. 500 ms for additional data events and only THEN process the data in the buffer. (Which is what the proxy by @UncleSamSwiss does.)

```
nextJob jobs.length=3
nextJob id=3003
startRead client.on data length=4
startRead client.on data length=1448
startRead client.on data length=1448
startRead client.on data length=1600
nextJob jobs.length=2
nextJob id=3004
startRead client.on data length=4
startRead client.on data length=1044
nextJob jobs.length=1
nextJob id=3005
startRead client.on data length=4
startRead client.on data length=353
nextJob jobs.length=0
nextJob closing connection
startRead client.close

nextJob jobs.length=3
nextJob id=3003
startRead client.on data length=4
startRead client.on data length=1448
startRead client.on data length=3048
nextJob jobs.length=2
nextJob id=3004
startRead client.on data length=4
startRead client.on data length=1044
nextJob jobs.length=1
nextJob id=3005
startRead client.on data length=4
startRead client.on data length=353
nextJob jobs.length=0
nextJob closing connection
startRead client.close

nextJob jobs.length=3
nextJob id=3003
startRead client.on data length=4
startRead client.on data length=1448
startRead client.on data length=2896
nextJob jobs.length=2
nextJob id=3004
startRead client.on data length=152
nextJob jobs.length=1
nextJob id=3005
startRead client.on data length=4
startRead client.on data length=1044
nextJob jobs.length=0
nextJob closing connection
startRead client.on data length=357
nextJob jobs.length=0
nextJob closing connection
17 Jan 21:31:29 - [red] Uncaught Exception:
17 Jan 21:31:29 - TypeError: Cannot read property 'end' of null
    at Luxtronik._nextJob (/Users/tm/Documents/Dev/luxtronik2/luxtronik.js:356:21)
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

**Comment by mnemo70** [comment]
I finally managed to understand the rest of the code. The "data" event function already concatenates additional received data events to the previously initialized payload buffer. It just stumbled over the initial error when it only receives 4 bytes, which was fixed by the "dataBuffer" that should only be used on the second "data" event. A third or fourth event should just result in a concatenation of the data to the previous payload.

The line "`if(data.length > 4)`" should probably read:
`if (data.length > 4 || this.receivy.activeCommand !== 0)`

Otherwise, a data event of 4 bytes would not be processed.

Also, change `data = this.dataBuffer` to:
```
const prevDataLength = data.length;
data = this.dataBuffer;
```
and change
`remaining: this.receivy[this.receivy.activeCommand].remaining - data.length,`
to:
`remaining: this.receivy[this.receivy.activeCommand].remaining - prevDataLength,`

This way, the remaining bytes are calculated correctly (which shouldn't really matter when remaining is tested for "<= 0", but still).

**Comment by UncleSamSwiss** [comment]
@mnemo70 Seems to make sense what you are proposing. Would you mind creating a PR for the repo owner to merge it back (it's much easier than trying to add your changes from your desscription). I'm not the owner, but I think we can expedite the testing when we already have a PR (I can start testing the PR with my heat pump).

**Comment by mnemo70** [comment]
> @mnemo70 Seems to make sense what you are proposing. Would you mind creating a PR for the repo owner to merge it back (it's much easier than trying to add your changes from your desscription). I'm not the owner, but I think we can expedite the testing when we already have a PR (I can start testing the PR with my heat pump).

Sure, I'll try. Just wanted to share my findings so that work isn't done twice. I'll need to think a bit more about what's happening, though.

**Comment by coolchip** [comment]
Thank you very much for all your research. I'm a litte bit busy at the time. But I will work on it if I get a bit of time.

**Comment by mnemo70** [comment]
Another realization: The dataBuffer should only be used on the second data event (after the initial 4 bytes are received). Otherwise it is always concatened in full to the internal "payload" of the command job, resulting in way too much data.

Also, we can skip concatenating the dataBuffer on subsequent events.

New code:
```
    this.client.on('data', function (data) {
        if (this.dataBuffer === undefined) {
            this.dataBuffer = data;
        }
        else
            if(this.dataBuffer.length === 4) {
                this.dataBuffer = Buffer.concat([this.dataBuffer, data]);
            }

        if (data.length > 4 || this.receivy.activeCommand !== 0) {
            if (this.receivy.activeCommand === 0) {
                data = this.dataBuffer;
                const commandEcho = data.readInt32BE(0);

```

**Comment by mnemo70** [comment]
Pull Request submitted!

**Comment by UncleSamSwiss** [comment]
> Pull Request submitted!

#16

**Comment by mnemo70** [comment]
Updated PR #16 to also correctly handle write.

**Comment by coolchip** [comment]
It is merged. Version 2.3.1 is on npm. 
Thank you all very, very much for your help.
