### ISSUE TITLE
Add heatingCurveEndPoint to _handleWriteCommand

### ISSUE THREAD

**Issue by TbsJah** [coolchip/luxtronik2#12]
https://github.com/coolchip/luxtronik2/blob/7e6dc944fbe8d739649e0826cc2d4234141adf1c/luxtronik.js#L479-L528

heatingCurveEndPoint should also be made configurable (get | set)

```
'heating_return_temperature':{
 setParameter: 11, 
 setValue: utils.value2LuxtronikSetValue(utils.limitRange(realValue, 20, 55)) 
 }
```

**Comment by coolchip** [comment]
Have added this in 2.1.0
