### ISSUE TITLE
heatingSystemCircPumpVoltage

### ISSUE THREAD

**Issue by TbsJah** [coolchip/luxtronik2#14]
Would be great if AO2 (voltage HUP) could be adjusted (heatingSystemCircPumpVoltage )
![image](https://user-images.githubusercontent.com/34193151/102822349-243eed00-43d9-11eb-8f18-d71a248f7562.png)
![image](https://user-images.githubusercontent.com/34193151/102822387-3ae54400-43d9-11eb-9a28-5da5fe60e55a.png)
![image](https://user-images.githubusercontent.com/34193151/102822596-b0511480-43d9-11eb-8b3c-6a0328b93978.png)

**Comment by coolchip** [comment]
Added in v2.2.0. Please test it.

**Comment by TbsJah** [comment]
Sorry, I named the wrong entries.
157 outputs only the current value of AO2.
The values 867 (voltage minimum) and 868 (voltage maximum) must be changed.

![image](https://user-images.githubusercontent.com/34193151/103528440-3febce00-4e84-11eb-89a0-c64e5c1c6bc0.png)

**Comment by coolchip** [comment]
Okay. Added values 867 and 868 with the names 'heating_system_circ_pump_voltage_nominal' and 'heating_system_circ_pump_voltage_minimal' and pushed it to version luxtronik2@2.3.0. Hope this helps. I used factor 100 for both. If this is not right, please write me.
