### ISSUE TITLE
Can't set temperature_hot_water_target

### ISSUE THREAD

**Issue by UncleSamSwiss** [coolchip/luxtronik2#18]
When I set the value of `warmwater_target_temperature` (write id=2), my heat pump display doesn't update the hot water target temperature.

When I change the hot water target temperature on the heat pump, it is not only `warmwater_temperature` (id=2) that changes, but also `temperature_hot_water_target` (id=105). My guess would be, one should set `temperature_hot_water_target` instead of `warmwater_target_temperature`.

**Comment by coolchip** [comment]
Thanks for this hint. I think the difference is heating with or without second heat source. Perhaps it should be possible to set both values.

**Comment by chrid88** [comment]
Hi @coolchip first of all thanks for porting the luxtronik2 adapter.
i have something to add to this issue, maybe it helps:
in the folder "parameters" there are 3 values concerning the hot_water_temperature:
- temperature_hot_water_limit
- temperature_hot_water_target
- warmwater_temperature

in my case temperature_hot_water_limit is set to 61°C, while in heat pump menu it says 65°C (this one i dont really understand)

Then I tried to understand, what the difference between temperature_hot_water_target and warmwater_temperature is (the latter can be modified using your adapter) and it led me to this menu in my heatpump:

<img width="446" alt="Bildschirmfoto 2021-03-04 um 17 44 27" src="https://user-images.githubusercontent.com/73813530/110078027-64cac780-7d87-11eb-83ac-2395d133ef63.png">

by changing warmwater temperature the value "Deckung WP" is changed.
But when i want to change the warmwater temperature in the heatpump i cant modify the "Deckung WP" but only "Wunschwert". "Wunschwert" seems to be what is called "temperature_hot_water_target".
So it would be great if you could add the possibility to edit this value!

**Comment by coolchip** [comment]
Thank you @chrid88. That is helpful. But I still have to wait for time to make this change.

**Comment by chrid88** [comment]
i am looking forward to seeing this, because it should give me the opportunity to dump my excess PV-energy into warmwater-generation. at the moment i need adjust it manually which sucks ;)

**Comment by TbsJah** [comment]
I already use the current version to raise the hot water temperature when there is enough power.
In combination with ioBroker, the great adapter from @UncleSamSwiss and a Blockly script
[https://github.com/UncleSamSwiss/ioBroker.luxtronik2/issues/10](url)

As long as the "Deckung" value is greater than the "Wunschwert" value, the assigned value is used for hot water production.

This behaviour is described in the controller manual. Sorry, unfortunately in German
![image](https://user-images.githubusercontent.com/34193151/111581747-1e7b5c80-87ba-11eb-9acd-bb8978839895.png)

![image](https://user-images.githubusercontent.com/34193151/111582502-330c2480-87bb-11eb-9765-74fef26e38a6.png)

**Comment by chrid88** [comment]
Hi @TbsJah , that looks indeed quite similar to my objective :)
iobroker is set up and i am experimenting with blockly. 
the only thing i dont quite understand is the first part, where you first check, if the operating mode has changed and if it changed to warmwater, you start the following tasks.
is there a specific reason that you check if your current operating mode is warmwater?
my idea is that i check if the operating mode is "keine Anforderung" or "Warmwasser"
to avoid that the heatpump starts clocking because of a variation in sun radiation i will use the excess energy's floating average of the last 15minutes. i suppose since it seems that you own a battery, this is not necessary for you.

**Comment by coolchip** [comment]
For the next release i've added:

        'temperature_hot_water_target': {
            setParameter: 105,
            setValue: utils.value2LuxtronikSetTemperatureValue(realValue)
        },

Hope that will help.
