### ISSUE TITLE
Missing Parameter: cooling_system_circ_pump_voltage_nominal

### ISSUE THREAD

**Issue by PG248** [coolchip/luxtronik2#22]
My AIT heat pump is equipped with passive cooling. In the Luxtronik setup menu there is a parameter Lstg. Kühlung (German) which ist the equivalent of heating_system_circ_pump_voltage_nominal but is used only when the heat pump is in cooling mode. It defines the power of the internal HUP when the heat pump is in cooling mode.

Would be nice, if you could add this to your library.

If you need more info, please tell me what you need.

**Comment by coolchip** [comment]
To add this value a need the ID. Can you find the value in the following list?
https://github.com/Bouni/Luxtronik-2/blob/master/documentation.md#meaning-of-the-data

Perhaps ID 1006?
