### ISSUE TITLE
"Mischkreis1" (MK1) missing

### ISSUE THREAD

**Issue by UncleSamSwiss** [coolchip/luxtronik2#26]
For my ioBroker Adapter which is based on your library, I got the following request:
https://github.com/UncleSamSwiss/ioBroker.luxtronik2/issues/123

> Ich habe die Heizkurve für den MK1 nicht gefunden. Die Heizkurve für den Heizkreis ist vorhanden und kann man auch erfolgreich setzen (heating_curve_end_point und heating_curve_parallel_offset).

> Nach Recherche müssten es diese Parameter sein:
14 - ID_Einst_HzMK1E_akt <-- Endpunkt Heizkurve MK1
15 - ID_Einst_HzMK1ANH_akt <-- Anhebung Heizkurve MK1
16 - ID_Einst_HzMK1ABS_akt <-- Nachtabsenkung Heizkurve MK1

Would you please be so kind to add these three variables?

**Comment by UncleSamSwiss** [comment]
Not sure if this is helpful, but my user found the following list of variables:
https://github.com/Bouni/Luxtronik-2/blob/master/documentation.md#meaning-of-the-data

**Comment by coolchip** [comment]
Added this for the next release. Looks like this:

heating_curve_end_point: 25.5
heating_curve_parallel_offset: 21.5
deltaHeatingReduction: 0
**mk1_curve_end_point: 26
mk1_curve_parallel_offset: 26
deltaMk1Reduction: 0**
