### ISSUE TITLE
TypeError: Cannot read property 'payload' of undefined 

### ISSUE THREAD

**Issue by tkirchm** [coolchip/luxtronik2#28]
Hello,

I get this error nearly every day and sometimes even up to five times.

> 2 Jan 02:00:23 - [red] Uncaught Exception:
2 Jan 02:00:23 - TypeError: Cannot read property 'payload' of undefined
at Luxtronik._processData (/home/pi/.node-red/node_modules/luxtronik2/luxtronik.js:332:74)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
nodered.service: Main process exited, code=exited, status=1/FAILURE
pam_unix(sudo:session): session closed for user root
nodered.service: Failed with result 'exit-code'.

**Comment by coolchip** [comment]
Perhaps this happens when the power supplier turns of your pump?
Will push a new version today. Hope this will fix it.
