### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by bakito** [coolchip/luxtronik2#4]
Hi
When I'm using 0.1.1 in https://github.com/bakito/pimatic-luxtronik2 I get the following error.

_Block-scoped declarations (let, const, function, class) not yet supported outside strict mode_

see: https://travis-ci.org/bakito/pimatic-luxtronik2/builds/221786054

I'm not quite sure what causes the problem, since my JavaScript Know-How is limitted.

Pimatic runns only on node 4.

Do you have any idea?

**Comment by coolchip** [comment]
Thats curious. I use the strict mode. I will check this later on.

**Comment by mwittig** [comment]
I think `"use strict";` must be added to all JS file used - see my pending pull request. With applied changes the travis build runs fine on my fork of pimatic-luxtronik2, see https://travis-ci.org/mwittig/pimatic-luxtronik2

**Comment by bakito** [comment]
Thank you guys very fast work of both of you.

**Comment by coolchip** [comment]
OMG.... My use stricks are gone. :-0
Thank you very much, mwittig.

**Comment by coolchip** [comment]
I will make an npm version soon this evening.

**Comment by coolchip** [comment]
Please give write again, if this don't fix your build error.

**Comment by bakito** [comment]
0.1.2 works for me, thank you
