### ISSUE TITLE
Warning message: Unknown data item parameters.solarPumpDeaerate

### ISSUE THREAD

**Issue by nase30** [coolchip/luxtronik2#43]
I have installed the luxtronic2 adapter. All data are visible (great job), but I get 2 warning messages: 
1. Unknown data item parameters.solarPumpDeaerate
2. Unknown data item parameters.runDeaerate

Does anybody have an idea how to fix it?
Regards
nase30

**Comment by MKs19862** [comment]
I have the same issue, could you already find a fix for this?

**Comment by grogo08** [comment]
I have the same issue. Did you get a solution / fix for your issue?

**Comment by coolchip** [comment]
Could be a difference between diferent pumps. Perhaps we can prevent this in the code. Which Pump do you use and when exactly do you get the warnings?

**Comment by boellner** [comment]
@nase30 what adapter luxtronic2 you mean that you have installed?
This project seems more than a library to me

**Comment by coolchip** [comment]
Yes, you are right, @boellner . This is only the library. I'll cole this. Please re-open and add details if there is still an issue.
