### ISSUE TITLE
warmwater_target_temperature bug

### ISSUE THREAD

**Issue by michiproep** [coolchip/luxtronik2#48]
The write parameter "warmwater_target_temperature" does not update (german) "Wunschtemperatur" but "Deckung WP".
"Deckung WP" is not even settable on the heappump display itself. 

Or do I have some misunderstanding?

**Comment by coolchip** [comment]
Thats curious. On my AIT heatpump it sets the "Wunschtemperatur". Which heatpump do you use? Do you use a second heater (heat stick)?

**Comment by michiproep** [comment]
Hi @coolchip,
in meantime I figured it out. It wasn't this library but iobroker.luxtronik wrongly hooked this datapoint, so I did a pullrequest there to fix it.
But what I did notice is that a lot of times when heatpump-state == -1 (unknown) things get instable. I did not debug it yet, just wanted to leave this note.
You can close this issue. Thanks.

**Comment by coolchip** [comment]
Thanks for your replay. If you want to you can open a new issue.
